config.toml.example

Seems like the example config is out-of-date vs current main.
Add placeholders for these values so users can more easily start up.

Fixup example config

---

Dockerfile

Results in a 22MB image locally, which is compressed to 7.78MB on docker hub!
Needs a GH action commit added next to auto-build and push. This [commit](https://github.com/0xB10C/fork-observer/commit/b50a0d519af1ed6283bab6dccfbc323be32d7ef6) shows a GH action to build and upload an image on *pushes* to main, and only build the image otherwise (on pull requests).
You should change the tags `tags: will8clark/fork-observer:latest` to use your own docker hub username, and you'll need to add secrets to the GH repo:
```
DOCKERHUB_USERNAME 
DOCKERHUB_PASSWORD
```

Docker alpine image-based

---

src/node.rs
www/index.html
www/js/blocktree.js

This includes a few fix-ups:
- frontend node list: 
- make list items smaller to use space more efficient
- sort by active tip height to better show lagging nodes
- allow list to collapse, but start with an un-collapsed list by default
- backend: fix a off-by-one error when using only REST that would skip the active tip when querying headers

Misc fixups

---

src/config.rs
src/node.rs
src/types.rs

With u8's, up to 256 nodes were possible. Warnet might want to use more nodes. Using an u32 instead of an u8 significantly increases the theoretical maximum.
closes #22

change: use u32 to represent node id's instead of u8

---

src/headertree.rs
src/main.rs
src/rss.rs
src/types.rs
www/css/style.css
www/index.html
www/js/main.js

contains output similar to e.g.
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
<channel>
<title>Invalid Blocks - Mainnet</title>
<description>Recent invalid blocks on the Bitcoin Mainnet network</description>
<item>
<title>Invalid block at height 809478</title>
<description>Invalid block 000000000000000000006840568a01091022093a176d12a1e8e5e261e4f11853 at height 809478 seen by node: Remote Node (id=0)</description>
<guid>000000000000000000006840568a01091022093a176d12a1e8e5e261e4f11853</guid>
</item>
<item>
<title>Invalid block at height 784121</title>
<description>Invalid block 000000000000000000046a2698233ed93bb5e74ba7d2146a68ddb0c2504c980d at height 784121 seen by node: Remote Node (id=0)</description>
<guid>000000000000000000046a2698233ed93bb5e74ba7d2146a68ddb0c2504c9 …
```

add: rss endpoint for invalid blocks

---

config.toml.example
src/config.rs
src/main.rs

This makes sure the `config.toml.example` file is up-to-date and that loading a configuration works.
Closes https://github.com/0xB10C/fork-observer/issues/14

add: test loading the example config file

---

config.toml.example
src/config.rs
src/main.rs
src/rss.rs

This tries to make the fork-observer RSS feeds valid according to the RSS 2.0 spec (using https://www.feedvalidator.org/). 
The newly added `rss_base_url` is optional and only required when actually using the RSS feeds (and needing valid RSS feeds).
closes https://github.com/0xB10C/fork-observer/issues/29

RSS spec conforming RSS feeds

---

Cargo.lock
Cargo.toml
README.md
config.toml.example
src/config.rs
src/db.rs
src/error.rs
src/headertree.rs
src/jsonrpc.rs
src/main.rs
src/node.rs
src/types.rs
www/css/style.css
www/js/blocktree.js
www/js/main.js

This adds optional pool identification by using the `getblock` RPC to query blocks and the https://crates.io/crates/bitcoin-pool-identification crate to identify pools. Blocks are queried and miners are updated in a separate thread.
This is a breaking change. It requires the database to be deleted. If the same nodes remain connected, no data should be lost as it's queried from the node again.
fixes: https://github.com/0xB10C/fork-observer/issues/28

Basic pool identification

---

src/api.rs
src/main.rs
src/rss.rs
src/types.rs
www/js/main.js

Probelems:
1. Some RSS feed readers aren't compatible with the rss/[feed].xml?network=X query argument.
2. Some RSS feed readers seem to require an unique <link></link> value.
Solutions:
1. Change to rss/[X]/[feed].xml. To be consistent across the backend, also change the api/data.json?network=X to api/[X]/data.json.
2. Link to [base_url]?network=X (front-end) instead of just the base URL

change: improve RSS feed compatibility

---

src/main.rs
src/rss.rs
src/types.rs
www/index.html
www/js/blocktree.js
www/js/main.js

Keep track of current node reachability in the backend, show it in the frontend, fix an error in the frontend allowing for unreachable nodes to be displayed, add an RSS feed for unreachable nodes.
closes https://github.com/0xB10C/fork-observer/issues/19

Add: node reachabillity 

---

src/config.rs
src/db.rs
src/headertree.rs
src/main.rs
src/types.rs

- moves some main() functionallity in smaller functions, more needed work here
- refactors the cache updates: upadetes are now handled by update_cache()
- while at it, fixes a race condition between miner identification and strip_tree where the just identified miner would be overwritten with a strip_tree result

refactor: big backend refactor

---

src/main.rs
www/fullscreen.html

Can be used for, for example, monitoring the halving.

add: full screen page under /fullscreen

---

www/css/style.css
www/js/blocktree.js

Instead of redrawing everything, the front-end now properly [joins](https://d3js.org/d3-selection/joining) the data to the SVG elements and only updates changed/new/removed blocks and links. This also allows showing animations for e.g. new blocks and links.
Showcase:
https://github.com/0xB10C/fork-observer/assets/19157360/d6de5db2-73ef-4149-81a0-a117c75da9b7

Improve and refactor d3 animations and data bindings

---

Cargo.lock
Cargo.toml

and rust-bitcoin-pool-indentification 0.3.3 -> 0.3.4.
bitcoincore-rpc 0.19 is needed for full Bitcoin Core >=28 support.
The getnetworkinfo RPC call now returns a list of warnings instead of a single warning String. This would cause fork-observer to fall back to "unkown version" as mapping the JSON response would fail.
See https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/356

upgrade: bitcoincore-rpc 0.18 -> 0.19

---

www/js/blocktree.js

Previously, node descriptions were capped at 20 chars before they would be hidden and rendered as an HTML details-summary element.
This had a few UX problems:
- users need to figure out that they can click on "description"
- users need to actually click on "description"
- https://github.com/bitcoin-dev-project/warnet/issues/656#issuecomment-2416906729
- https://github.com/bitcoin-dev-project/warnet/issues/656#issuecomment-2417351164
To improve this, long node descriptions are now trucated once they would wrap. Upon clicking on them, they are expanded. Now, a user sees the start of the node description (as opposed to only seeing "description") while the node box sizes still are the same on initial page load.

improve handling of long node descriptions

---

www/css/style.css
www/index.html
www/js/blocktree.js

closes https://github.com/0xB10C/fork-observer/issues/53 by showing a legend for the colors in the top right corner. hovering over the tip status gives a longer description.

add: legend for tip status

---

Cargo.lock
Cargo.toml
README.md
src/config.rs
src/error.rs
src/node.rs

closes #52 by allowing to connect fork-observer to esplora (e.g. blockstream.info and mempool.space) based block explorers

add: enable connecting to esplora backends 

---

src/api.rs
src/main.rs
www/js/main.js

This allows us to react more timely to cache changes. Otherwise, it frequently happend that we displayed a node as lagging behind for a while until we fetched data for the next block. We queue very frequent data fetches up on the frontend, but frequently hitting the backend shouldn't be a problem, as the backend caches the responses.

add: notify frontend on all cache changes

---

src/main.rs
src/types.rs

btcd would return the same chaintips in a different order, which caused us to think they aren't the same as the previous. Sort them to be sure they can be compared.

fix: sort chaintips before comparing them

---

.github/dependabot.yml

Dependabot will open PRs for direct Rust dependecies that need updating.

add: dependabot updates for direct Rust depends

---

Cargo.lock
Cargo.toml
README.md
config.toml.example
src/config.rs
src/error.rs
src/main.rs
src/node.rs
www/js/blocktree.js

This adds support for connecting to Electrum servers as data sources. While the Electrum protocol does not inform about chain tips and only allows fetching headers by height and not hash, together with a Bitcoin Core or btcd node, this allows for nice insights into stale block propagation across the network when connecting to multiple public Electrum servers.
Closes #51 
```toml
[[networks.nodes]]
id = 3
name = "Electrum Emzy"
description = "URL electrum.emzy.de:50002"
rpc_host = "ssl://electrum.emzy.de"
rpc_port = 50002
implementation = "electrum"
```

Add Electrum backend support

---

.github/dependabot.yml

These are too noisy. We only really care about:
- version-update:semver-minor
- version-update:semver-major

dependabot: ignore semver-patch updates
